package main;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Admin
 */
public class NetBankingPage extends javax.swing.JFrame {

    private String str;

    /**
     * Creates new form NetBankingPage
     *
     * @param username
     */
    public NetBankingPage() {
        initComponents();
        
    }

    public NetBankingPage(String username) {
        initComponents();
        str = username;

    }

    public String getUserName() {
        return this.str;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        balance = new javax.swing.JButton();
        deposit = new javax.swing.JButton();
        transfer = new javax.swing.JButton();
        displayDetails = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        displayDetails1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Banking Operations");

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\OneDrive\\Desktop\\JAVA PROJECT\\images\\bank-icon-logo-vector-260nw-399995245.png")); // NOI18N

        balance.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        balance.setText("CHECK BALANCE");
        balance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balanceActionPerformed(evt);
            }
        });

        deposit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        deposit.setText("DEPOSIT");
        deposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositActionPerformed(evt);
            }
        });

        transfer.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        transfer.setText("TRANSFER ");
        transfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferActionPerformed(evt);
            }
        });

        displayDetails.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        displayDetails.setText("DISPLAY DETAILS");
        displayDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayDetailsActionPerformed(evt);
            }
        });

        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        displayDetails1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        displayDetails1.setText("DISPLAY STATEMENT");
        displayDetails1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayDetails1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(balance, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deposit, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(transfer, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(displayDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(displayDetails1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(120, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(111, 111, 111))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(63, 63, 63))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(balance)
                .addGap(28, 28, 28)
                .addComponent(deposit)
                .addGap(28, 28, 28)
                .addComponent(transfer)
                .addGap(28, 28, 28)
                .addComponent(displayDetails)
                .addGap(28, 28, 28)
                .addComponent(displayDetails1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void depositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositActionPerformed
        String username = this.getUserName();
        System.out.println("NetBankingPage : Deposit button pressed for username " + username);
        new Deposit(username).setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_depositActionPerformed

    private void transferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferActionPerformed
         new Transfer(this.getUserName()).setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_transferActionPerformed

    private void balanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_balanceActionPerformed
        String username = this.getUserName();
        System.out.println("NetBankingPage : Check balance button pressed for username " + username);
        new Balance(username).setVisible(true);

// TODO add your handling code here:
    }//GEN-LAST:event_balanceActionPerformed

    private void displayDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayDetailsActionPerformed
           
        try {
             ConnectionHelper ch =new ConnectionHelper();
            Connection con =ch.getConnection();
            Statement stmt = con.createStatement();
            
            String query =String.format("select * from customerdetails where emailId='%s'",this.getUserName());
            ResultSet rs=stmt.executeQuery(query);
            if(rs.next()){
                
            }//"name:%s \nAccount number: \nbankBalance: \nssn: \nphone number: \ngender: \nemailId: "
            String name=rs.getString("name");
            String phNo=rs.getString("phoneNumber");
            String gender=rs.getString("gender");
            String emailId=rs.getString("emailId");
            String ssn=rs.getString("ssn");
            String bankBalance=rs.getString("BankBalance");
            String accNo=rs.getString("accNo");
            System.out.println("name: "+name);
            System.out.println("acc No: "+ accNo);
            
        new DisplayDetails(this.getUserName()).setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(NetBankingPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        

       // TODO add your handling code here:
    }//GEN-LAST:event_displayDetailsActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
          this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void displayDetails1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayDetails1ActionPerformed
        new DisplayStatement(this.getUserName()).setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_displayDetails1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NetBankingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NetBankingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NetBankingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NetBankingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {

            new NetBankingPage().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton balance;
    private javax.swing.JButton deposit;
    private javax.swing.JButton displayDetails;
    private javax.swing.JButton displayDetails1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton transfer;
    // End of variables declaration//GEN-END:variables
}
